name: Trigger Netlify Build
on:
  push:
    branches:
      - 'trial-deploy'
  schedule:
    - cron: '0 0 * * *' # Once a day
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        run: curl -X POST -d {} ${{ secrets.NETLIFY_HOOK }}