name: Trigger Vercel Build
on:
  schedule:
    - cron: '0 0 * * *' # Once a date
jobs:
  build:
    name: Request Vercel Webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        run: curl -X POST -d {} ${{ secrets.VERCEL_HOOK }}
